---
title: "WMO Analysis"
author: "Theodros H."
date: "3/6/2019"
output: 
  html_document:
    code_folding: hide
---
#EXCLUDED 625
WMO Analysis
There are 8 blocks of set size 3 trials and 6 blocks of set size 6 trials per participant for a total of 14 blocks
```{r start up, echo=FALSE, message=FALSE, warning=FALSE}
#
rm(list = ls())
library(matlab)
library(tidyverse)
library(magrittr)

```
Import data and set variables
```{r}

#Import data
wmodata     <- read.csv('./processed_data/wmo_training_2023.txt') 
wmotestdata <- read.csv('./processed_data/wmo_test_06_2023.txt') 


Training.blocks <- c(3,6,3,3,6,3,6,6,3,3,6,3,6,3) #from data
block.3 <- which(Training.blocks==3)
block.6 <- which(Training.blocks==6)
#logical indices
ns3 <- wmodata$trial==39
ns6 <- wmodata$trial==78
#variable declaration as determined by saved data
wmo.N.trials <- 780 
ns3.blks <- 8 
ns6.blks <- 6
ns3.n <- 3
ns6.n <- 6
#maintain a universal list of participants
#Subs <- unique(wmodata$subject)#this will change

Subjects <- as.matrix(read.csv('stag_2023_subjects.csv',header = FALSE))

# excluded subjects 
# ---- 7532,  don't know why yet
 Subjects[Subjects=='7532']=0
```
 
This block performs the learning/accuracy curve: acc by item`r ns6` iteration  

#### NOTE: plot titles are: ID number / fit coefficient for set 3 / fit coefficient for set 6 


```{r, echo=FALSE, message=FALSE, warning=FALSE}
i=1
mean.acc.3 <- c()
mean.acc.6 <- c() 
wmo.s <- c()
Missing.p <- c()
learningRate.3 <- c()
learningRate.6 <- c()
#Subjects=7515
#iterate through each subject here:
for (s in Subjects) {
OneSub <- wmodata$subject == s  
if(any(OneSub)==1){

#rehsape script here: this reshapes response vector in to trial x block
#use these to find the trials
temp.sort.3 <- reshape(as.matrix(wmodata$seq[OneSub & ns3]),39,ns3.blks)
temp.sort.6 <- reshape(as.matrix(wmodata$seq[OneSub & ns6]),78,ns6.blks)
#these are the actual data. 
temp.dat.3 <- reshape(as.matrix(wmodata$acc[OneSub & ns3]),39, ns3.blks)
temp.dat.6 <- reshape(as.matrix(wmodata$acc[OneSub & ns6]),78, ns6.blks)
#iterate through blocks here:
temp.cat.3 <- c()
temp.cat.6 <- c()

for (n in 1:ns3.blks) {
  #iterate through items here
 #temp.cat.3<- cbind(temp.cat.3,reshape(as.matrix(sort(temp.sort.3[,n])),13,3)) #accumulates across blocks
 
  temp.cat.3<-cbind(temp.cat.3,cbind(as.matrix(temp.dat.3[temp.sort.3[,n]==1,n][1:12]),
                                     as.matrix(temp.dat.3[temp.sort.3[,n]==2,n][1:12]),
                                      as.matrix(temp.dat.3[temp.sort.3[,n]==3,n][1:12])
                                     )
                    )
   if(TRUE){ 
     if (n <= ns6.blks) {
          temp.cat.6<-cbind(temp.cat.6,cbind(as.matrix(temp.dat.6[temp.sort.6[,n]==1,n][1:12]),
                                      as.matrix(temp.dat.6[temp.sort.6[,n]==2,n][1:12]),
                                      as.matrix(temp.dat.6[temp.sort.6[,n]==3,n][1:12]),
                                      as.matrix(temp.dat.6[temp.sort.6[,n]==4,n][1:12]),
                                      as.matrix(temp.dat.6[temp.sort.6[,n]==5,n][1:12]),
                                      as.matrix(temp.dat.6[temp.sort.6[,n]==6,n][1:12])
                                     )
          )
          }
     }
 
} 
#clean missing values -1 
temp.cat.6[temp.cat.6==-1]=0
temp.cat.3[temp.cat.3==-1]=0
#save subject
wmo.s[i] <- s


 mean.acc.3 <-cbind(mean.acc.3,rowMeans(temp.cat.3,na.rm = FALSE)) # accumulates across subjects
 mean.acc.6 <-cbind(mean.acc.6,rowMeans(temp.cat.6,na.rm = FALSE))
 #print(length(rowMeans(temp.cat.6,na.rm = TRUE)))
 #dataframes for model fits
 tempframe.3 <- data.frame("accuracy" =rowMeans(temp.cat.3),
                          "iterations" = 1:12 )
tempframe.6 <- data.frame("accuracy" =rowMeans(temp.cat.6),
                          "iterations" = 1:12 )
temp.lm.3 <- lm(accuracy ~ poly(iterations,4), data = tempframe.3)
temp.lm.6 <- lm(accuracy ~ poly(iterations,4), data = tempframe.6)
 
  if (1) {
   
 
    plot(rowMeans(temp.cat.3),ylim = c(0,1),col = '#e41a1c',
          cex=1,lwd=2,pch=19, xlab ='Stimulus presentations',
          ylab ='Accuracy', main = s)
    #c(s,   round(summary(temp.lm.3)$coefficients[4,1],3),round(summary(temp.lm.6)$coefficients[4,1],3)

 
    #lines(rowMeans(temp.cat.3),ylim = c(0,1),col = 'green4',lwd=2)
    points(rowMeans(temp.cat.6),ylim = c(0,1),col = '#377eb8',pch=19,cex=1,lwd=2)
    #lines(rowMeans(temp.cat.6),ylim = c(0,1),col = 'orange',lwd=2)
    legend("bottomright", c("set size 3", "set size 6"),pch = c( 19, 19),
           text.col =c( "#e41a1c","#377eb8"), col = c("#e41a1c","#377eb8"))

    lines(tempframe.3$iterations,temp.lm.3$fitted.values,lwd=2.3, col = '#e41a1c')
    lines(tempframe.6$iterations,temp.lm.6$fitted.values,lwd=2.3, col = '#377eb8')
  }

learningRate.3[i] <- round(summary(temp.lm.3)$coefficients[4,1],3)
learningRate.6[i] <- round(summary(temp.lm.6)$coefficients[4,1],3)


i = i+ 1
}
else {
  #use this to track missing data
  Missing.p[i] <-s 
  
mean.acc.3 <-cbind(mean.acc.3,rep(NA,12)) # accumulates across subjects
mean.acc.6 <-cbind(mean.acc.6,rep(NA,12))
}
}
# set size 3 vs set size 6 performance indicator: subtract the two and take the average for each iteration point. A negative number indicates better performance, overall in set size 6, no difference if close to zero

wmo.learn.score <- colMeans(mean.acc.3-mean.acc.6)

```

```{r analyze test data}
ns3.test.mean <- c()
ns6.test.mean <- c()
i = 1
for (s in Subjects) {
  OneSub <- wmotestdata$subject==s  
  ns3.test.mean[i] <- mean(wmotestdata[!is.na(match(wmotestdata[,"stim"],block.3)) & OneSub,"acc"])
  ns6.test.mean[i] <- mean(wmotestdata[!is.na(match(wmotestdata[,"stim"],block.6)) & OneSub,"acc"])

  i = i + 1
}
TestData=data.frame(ns3.test.mean,ns6.test.mean)

```



```{r export data}
if(1){
  
mean.acc.3 %<>% t()
mean.acc.6 %<>% t()
colnames(mean.acc.3) = paste0('learn3_',1:12)
colnames(mean.acc.6) = paste0('learn6_',1:12)
rlwm_data <-  cbind(mean.acc.3, mean.acc.6) %>% 
  as_data_frame()
 
  
ns3_test <- rep(ns3.test.mean,12) %>% 
    as.matrix() %>% 
    reshape(., numel(ns3.test.mean),12) %>%
    as_data_frame()
  
colnames(ns3_test) <- paste0('test3_', 1:12)

  ns6_test <-  rep(ns6.test.mean,12) %>% 
    as.matrix() %>% 
    reshape(., numel(ns6.test.mean),12) %>%
    as_data_frame()
colnames(ns6_test) <- paste0('test6_', 1:12)

rlwm_data %<>% 
  cbind(ns3_test, ns6_test) %>% 
   mutate(subjects = Subjects %>% c()) %>% 
  drop_na()

write_csv(rlwm_data, 'RLWM_data_stag052023.csv')

}

RLWM_test_new <- wmotestdata %>%  
  rename(response = Code, 
         imageID = stim, 
         blockID = block) %>% 
  mutate(stimetSize =  
           case_when(blockID == 2 ~ 6, 
                     blockID == 3 ~ 3, 
                     blockID == 4 ~ 3, 
                     blockID == 5 ~ 6, 
                     blockID == 6 ~ 3, 
                     blockID == 7 ~ 6, 
                     blockID == 8 ~ 6, 
                     blockID == 9 ~ 3, 
                     blockID == 10 ~ 3, 
                     blockID == 11 ~ 6, 
                     blockID == 12 ~ 3, 
                     blockID == 13 ~ 6))



write_csv(RLWM_test_new, 'RLWM_TEST_data_stag_06_2023.csv')
```

```{r}
dat = read_csv('one_subject_fit.csv')

dat %>% 
  drop_na() %>% 
  inner_join(tibble(blockSize = c(3,6,3,3,6,3,6,6,3,3,6,3,6,3), 
                    block=1:14), by='block') %>% 
  filter(blockSize==3, image==2, block==6) %>% 

arrange(block, image) %>% 
  group_by(block, image) %>% 
  mutate(index_bi = row_number()) %>%  
 # ungroup() %>% skimr::skim()
  group_by(index_bi, response) %>% 
  
  
  summarise(mean=mean(Q),
         n=n(),
            se=std(Q)/sqrt(n))  %>% 
   ggplot(aes(x=index_bi, y=mean, 
              ymax=mean+se, ymin=mean-se, 
              group=response, color=as.factor(response))) +
  geom_point(size=5) +
  geom_line(size=2) +
  theme_pubclean(base_size = 28, base_family = 'Times', ) +
  xlab("Trials")+
  ylab('Utility (U)') 
  
 
 
  
  

```

